version: "3.3"
services:
        web:
                image: example/my_web_app:latest
                depends_on:
                - db
                - cache

        db:
                image: postgres:latest

        cache:
                image: redis:latest

